ARG VERSION
FROM kometateam/kometa:${VERSION}

ARG VERSION

LABEL org.opencontainers.image.title="kometa" \
      org.opencontainers.image.version="${VERSION}" \
      org.opencontainers.image.url="https://github.com/action3062/containers/tree/main/apps/kometa" \
      org.opencontainers.image.source="https://github.com/Kometa-Team/Kometa"
