ARG VERSION
FROM ghcr.io/immichframe/immichframe:${VERSION}

ARG VERSION

LABEL org.opencontainers.image.title="immichframe" \
      org.opencontainers.image.version="${VERSION}" \
      org.opencontainers.image.url="https://github.com/action3062/containers/tree/main/apps/immichframe" \
      org.opencontainers.image.source="https://github.com/immichFrame/ImmichFrame"

EXPOSE 8080
