ARG VERSION
FROM sissbruecker/linkding:${VERSION}

ARG VERSION

LABEL org.opencontainers.image.title="linkding" \
      org.opencontainers.image.version="${VERSION}" \
      org.opencontainers.image.url="https://github.com/action3062/containers/tree/main/apps/linkding" \
      org.opencontainers.image.source="https://github.com/sissbruecker/linkding"

EXPOSE 9090
