ARG VERSION
FROM dullage/flatnotes:v${VERSION}

ARG VERSION

LABEL org.opencontainers.image.title="flatnotes" \
      org.opencontainers.image.version="${VERSION}" \
      org.opencontainers.image.url="https://github.com/action3062/containers/tree/main/apps/flatnotes" \
      org.opencontainers.image.source="https://github.com/dullage/flatnotes"

EXPOSE 8080
