ARG VERSION
FROM daya0576/beaverhabits:${VERSION}

ARG VERSION

LABEL org.opencontainers.image.title="beaverhabits" \
      org.opencontainers.image.version="${VERSION}" \
      org.opencontainers.image.url="https://github.com/action3062/containers/tree/main/apps/beaverhabits" \
      org.opencontainers.image.source="https://github.com/daya0576/beaverhabits"

EXPOSE 8080
