ARG VERSION
FROM ghcr.io/tarampampam/error-pages:${VERSION}

ARG VERSION

LABEL org.opencontainers.image.title="error-pages" \
      org.opencontainers.image.version="${VERSION}" \
      org.opencontainers.image.url="https://github.com/action3062/containers/tree/main/apps/error-pages" \
      org.opencontainers.image.source="https://github.com/tarampampam/error-pages"

EXPOSE 8080
