ARG VERSION
FROM ghcr.io/cleanuparr/cleanuparr:${VERSION}

ARG VERSION

LABEL org.opencontainers.image.title="cleanuparr" \
      org.opencontainers.image.version="${VERSION}" \
      org.opencontainers.image.url="https://github.com/action3062/containers/tree/main/apps/cleanuparr" \
      org.opencontainers.image.source="https://github.com/Cleanuparr/Cleanuparr"

EXPOSE 11011
