ARG VERSION
FROM g0ldyy/comet:${VERSION}

ARG VERSION

LABEL org.opencontainers.image.title="comet" \
      org.opencontainers.image.version="${VERSION}" \
      org.opencontainers.image.url="https://github.com/action3062/containers/tree/main/apps/comet" \
      org.opencontainers.image.source="https://github.com/g0ldyy/comet"

EXPOSE 8000
