ARG VERSION
FROM ghcr.io/sysadminsmedia/homebox:${VERSION}

ARG VERSION

LABEL org.opencontainers.image.title="homebox" \
      org.opencontainers.image.version="${VERSION}" \
      org.opencontainers.image.url="https://github.com/action3062/containers/tree/main/apps/homebox" \
      org.opencontainers.image.source="https://github.com/sysadminsmedia/homebox"

EXPOSE 7745
