ARG VERSION
FROM cyfershepard/jellystat:${VERSION}

ARG VERSION

LABEL org.opencontainers.image.title="jellystat" \
      org.opencontainers.image.version="${VERSION}" \
      org.opencontainers.image.url="https://github.com/action3062/containers/tree/main/apps/jellystat" \
      org.opencontainers.image.source="https://github.com/CyferShepard/Jellystat"

EXPOSE 3000
