ARG VERSION
FROM muniftanjim/stremthru:${VERSION}

ARG VERSION

LABEL org.opencontainers.image.title="stremthru" \
      org.opencontainers.image.version="${VERSION}" \
      org.opencontainers.image.url="https://github.com/action3062/containers/tree/main/apps/stremthru" \
      org.opencontainers.image.source="https://github.com/MunifTanjim/stremthru"

EXPOSE 8080
