ARG VERSION
FROM b4bz/homer:${VERSION}

ARG VERSION

LABEL org.opencontainers.image.title="homer" \
      org.opencontainers.image.version="${VERSION}" \
      org.opencontainers.image.url="https://github.com/action3062/containers/tree/main/apps/homer" \
      org.opencontainers.image.source="https://github.com/bastienwirtz/homer"

EXPOSE 8080
