ARG VERSION
FROM freshrss/freshrss:${VERSION}

ARG VERSION

LABEL org.opencontainers.image.title="freshrss" \
      org.opencontainers.image.version="${VERSION}" \
      org.opencontainers.image.url="https://github.com/action3062/containers/tree/main/apps/freshrss" \
      org.opencontainers.image.source="https://github.com/FreshRSS/FreshRSS"

EXPOSE 80
